version: '3.8'

services:
  # Backend FastAPI
  backend:
    build:
      context: .
    container_name: taskmanager_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    depends_on:
      - mongodb
    networks:
      - taskmanager_network
    restart: unless-stopped

  # MongoDB Database
  mongodb:
    image: mongo:7.0-jammy
    container_name: taskmanager_mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=taskmanager
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - taskmanager_network
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local

networks:
  taskmanager_network:
    driver: bridge 